
import os

MAX_ERROR = int(os.getenv('ACT_MAX_ERROR', '1000'))
MAX_WARNING = int(os.getenv('ACT_MAX_WARNING', '10000'))
MAX_LOG_SIZE = int(os.getenv('ACT_MAX_LOG_SIZE', '200'))
DEFAULT_RUN_TIMEOUT = int(os.getenv('ACT_RUN_TIMEOUT', '86400'))
LABELS_DEV_STATUS = ['TODO', 'ONGOING', 'DONE']
LABELS_DEV_STATUS_IGNORE = ['NOTPLANNED']
LABELS_DEV_STATUS_ALL = LABELS_DEV_STATUS + LABELS_DEV_STATUS_IGNORE

